import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/navbar'
import Footer from '@/components/footer'
import Top from '@/components/top'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Ladie's point",
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='max-w-[90%] mx-auto'>
          <Top/>
        <Navbar/>
        {children}
        <Footer/>
        </div>
        </body>
    </html>
  )
}
